### ISSUE TITLE
Android Emulator - x86 - API30 - Google API's not created.

### ISSUE THREAD

**Issue by n-x-p** [Redth/dotnet-maui-check#28]
![image](https://user-images.githubusercontent.com/4811056/118417696-47698200-b683-11eb-8560-cf62825ad14e.png)

**Comment by kawa0710** [comment]
I got the same problem.
I had fixed by the flowing steps:
1. installing Android Studio. After that I encounter "Unable to run Android Emulator Hypervisor Driver fo AMD Processor installer"
2. disable Hyper-V in Windows 10 and enable SVM in BIOS.

Perhaps it caused by AMD CPU

**Comment by n-x-p** [comment]
I'll try that, thanks!

**Comment by n-x-p** [comment]
That seemed to fix my issue

**Comment by WolfManR** [comment]
there was the same error, went into the studio, opened the emulator manager and created it manually for API 30

**Comment by himpire** [comment]
I tried the solution by @kawa0710  but still getting the same error.
 I have a Hp Zbook core i7 4MQ 
I even tried to Install Android tools using Android Studio but still the problem exists

**Comment by n-x-p** [comment]
I don't think the processor matters in this case as I was running an i7 9700.

**Comment by iclcs** [comment]
I installed VS 16.11 Preview 1 with these selected workloads:
* ASP.NET and web development
* .NET desktop development
* Mobile development with .NET
* .NET cross-platform development
I manually installed .NET 6.0 Preview 4 (both x86 and x64).
I ran "dotnet tool install -g redth.net.maui.check" from the Developer Command Prompt for VS 2019 Preview.
I ran dotnet --info just to check that it's running on .NET 6.
I ran maui-check and encountered the error mention in this issue.
I skipped and let it do the rest.
I came back to the Visual Studio Installer to check a few things and found out that under Emulators (tab: Individual components) there was nothing installed! So I check the Google Android Emulator (API Level 25) (local install) - which checked other things as well (like the HAXM) and updated the installation (click on Modify).
I ran again maui-check and surprise, it told me now that everything is fine!
Maybe this will help someone else... if they are lucky as me :)

**Comment by malikhammad113** [comment]
Hxam driver installation error

**Comment by malikhammad113** [comment]
How can I fix it
